############My Sql Settings#########

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: kumar123
    platform: msql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql


############Oracle connection##########
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@192.168.2.5:1521/xepdb1
#    username: hr
#    password: Oracle2018
#    platform: oracle
#    dbcp2:
#      test-while-idle: true
#      validation-query: select 1
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    database-platform: org.hibernate.dialect.OracleDialect
#    database: oracle
#    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql